# Generated by Django 5.0.7 on 2024-07-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_quillpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
