# Generated by Django 5.0.7 on 2024-07-28 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_alter_quillpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quillpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
